export const REGISTER_REQUESTING = "REGISTER_REQUESTING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const RESET_APP = "RESET_APP";

export const IS_UNIQUE_USERNAME_REQUESTING = "IS_UNIQUE_USERNAME_REQUESTING";
export const IS_UNIQUE_USERNAME_SUCCESS = "IS_UNIQUE_USERNAME_SUCCESS";
export const IS_UNIQUE_USERNAME_ERROR = "IS_UNIQUE_USERNAME_ERROR";

export const IS_UNIQUE_EMAIL_REQUESTING = "IS_UNIQUE_EMAIL_REQUESTING";
export const IS_UNIQUE_EMAIL_SUCCESS = "IS_UNIQUE_EMAIL_SUCCESS";
export const IS_UNIQUE_EMAIL_ERROR = "IS_UNIQUE_EMAIL_ERROR";
