export const USERS_REQUESTING = "USERS_REQUESTING";
export const USERS_SUCCESS = "USERS_SUCCESS";
export const USERS_ERROR = "USERS_ERROR";

export const USER_REQUESTING = "USER_REQUESTING";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_ERROR = "USER_ERROR";

export const USER_SAVE_REQUESTING = "USER_SAVE_REQUESTING";
export const USER_SAVE_SUCCESS = "USER_SAVE_SUCCESS";
export const USER_SAVE_ERROR = "USER_SAVE_ERROR";

export const USER_DELETE_REQUESTING = "USER_DELETE_REQUESTING";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_ERROR = "USER_DELETE_ERROR";

export const CHANGE_PASSWORD_REQUESTING = "CHANGE_PASSWORD_REQUESTING";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ERROR = "CHANGE_PASSWORD_ERROR";
