export const USERS_REQUESTING = "USERS_REQUESTING";
export const USERS_SUCCESS = "USERS_SUCCESS";
export const USERS_ERROR = "USERS_ERROR";
export const USER_EDIT = "USER_EDIT";
export const USER_SAVE = "USER_SAVE";
export const USER_DELETE = "USER_DELETE";

export const IS_UNIQUE_USERNAME_REQUESTING = "IS_UNIQUE_USERNAME_REQUESTING";
export const IS_UNIQUE_USERNAME_SUCCESS = "IS_UNIQUE_USERNAME_SUCCESS";
export const IS_UNIQUE_USERNAME_ERROR = "IS_UNIQUE_USERNAME_ERROR";

export const IS_UNIQUE_EMAIL_REQUESTING = "IS_UNIQUE_EMAIL_REQUESTING";
export const IS_UNIQUE_EMAIL_SUCCESS = "IS_UNIQUE_EMAIL_SUCCESS";
export const IS_UNIQUE_EMAIL_ERROR = "IS_UNIQUE_EMAIL_ERROR";
